import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Alarm from "@/components/Alarm";
import About from "@/components/About";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <main className="flex max-w-2xl flex-col items-center mx-auto justify-between">
          {/* <Navbar /> */}
          {children}

          <About />
        </main>
      </body>
    </html>
  );
}
